>P1;UKNP
sequence:UKNP:1    :A:465  :A::::
MSKSTAEIRQAFLDFFHSKGHQVVASSSLVPHNDPTLLFTNAGMNQFKDVFLGLDKRNY-----SRATTSQRCVRAGGKHNDLENVGYTARHHTFFEMLGNFSFGDYFKHDAIQFAWELLTSEKWFALPKERLWVTVYESDD--------EAYEIWEKEVGIPRERIIRIGDNKGAPYASDNFWQMGDTGPCGPCTEIFYDHGDHIWGGPPGSPEEDGDRYIEIWNIVFMQFNRQADGTMEPLPKPSVDTGMGLERIAAVLQHVNSNYDIDLFRTLIQAVAKVTGAT-----------DLSNKSLRVIADHIRSCAFLIADGVMPSNENRGYVLRRIIRRAVRHGNM-LGAKETFFYKLVGPLIDVMGSAGEDLKRQQAQVEQVLKTEEEQFARTLERGLALLDEELAKL-SGDTLDGETAFRLYDTYGFPVDLTADVCRERNIKVDEAGFEAAMEEQRRRAREA*
>P1;4XEO
structure:modified_cif/4XEO.cif:23  :B:405 :B::Homo sapiens:1.38:
STLTASEIRQRFIDFFKRNEHTYVHSSATIPLDDPTLLFANAGMNQFKPIFLNTIDPSHPMAKLSRAANTQKCIRA-----DLDDVGKDVYHHTFFEMLGSWSFGDYFKELACKMALELLTQ--EFGIPIERLYVTYFGGDEAAGLEADLECKQIWQN-LGLDDTKILPGN-------MKDNFWEMGDTGPCGPCSEIHYDRIGGRDAA--HLVNQDDPNVLEIWNLVFIQYNREADGILKPLPKKSIDTGMGLERLVSVLQNKMSNYDTDLFVPYFEAIQKGTGARPYTGKVGAEDADGIDMAYRVLADHARTITVALADGGRPDNTGRGYVLRRILHRAVRYAHEKLNASRGFFATLVDVVVQSLGDAFPELKKDPDMVKDIINEEEVQFLKT----------------------------------------------------------------------*

