>P1;UKNP
sequence:UKNP:1    :A:465  :A::::
MSKSTAEIRQAFLDFFHSKGHQVVASSSLVPHNDPTLLFTNAGMNQFKDVFLGLDKR-----NYSRATTSQRCVRAGGKHNDLENVGYTARHHTFFEMLGNFSFGDYFKHDAIQFAWELLTSEKWFALPKERLWVTVYESDD--------EAYEIWEKEVGIPRERIIRIGDNKGAPYASDNFWQMGDTGPCGPCTEIFYDHGDHIWGGPPGSPEEDGDRYIEIWNIVFMQFNRQADGTMEPLPKPSVDTGMGLERIAAVLQHVNSNYDIDLFRTLIQAVAKVTGAT-----------DLSNKSLRVIADHIRSCAFLIADGVMPSNENRGYVLRRIIRRAVRHGNM-LGAKETFFYKLVGPLIDVMGSAGEDLKRQQAQVEQVLKTEEEQFARTLERGLALLDEELAKL-SGDTLDGETAFRLYDTYGFPVDLTADVCRERNIKVDEAGFEAAMEEQRRRAREA*
>P1;5V59
structure:modified_cif/5V59.cif:24  :A:404 :A::Homo sapiens:2.03:
-TLTASEIRQRFIDFFKRNEHTYVHSSATIPLDDPTLLFANAGMNQFKPIFLNTIDPSHPMAKLSRAANTQKCIRAGG--NDLDDVGKDVYHHTFFEMLGSWSFGDYFKELACKMALELLTQ--EFGIPIERLYVTYFGGDEAAGLEADLECKQIWQN-LGLDDTKILPGN-------MKDNFWEMGDTGPCGPCSEIHYDRIGGRDAA--HLVNQDDPNVLEIWNLVFIQYNREADGILKPLPKKSIDTGMGLERLVSVLQNKMSNYDTDLFVPYFEAIQKGTGARPYTGKVGAEDADGIDMAYRVLADHARTITVALADGGRPDNTGRGYVLRRILRRAVRYAHEKLNASRGFFATLVDVVVQSLGDAFPELKKDPDMVKDIINEEEVQFLK-----------------------------------------------------------------------*

